<?php
// idioma.php

// Establecer idioma por defecto
$idioma = 'es';

// Si se envía un nuevo idioma por POST/GET, actualizar la cookie
if (isset($_REQUEST['lang']) && in_array($_REQUEST['lang'], ['es', 'en'])) {
    $idioma = $_REQUEST['lang'];
    // Cookie que dura 30 días
    setcookie('idioma', $idioma, time() + (86400 * 30), '/', '', false, true);
}

// Si existe la cookie de idioma, usarla
if (isset($_COOKIE['idioma']) && in_array($_COOKIE['idioma'], ['es', 'en'])) {
    $idioma = $_COOKIE['idioma'];
}

// Textos en ambos idiomas
$textos = [
    'es' => [
        'hotel_nombre' => 'Hotel El Gran Descanso',
        'login_titulo' => '🔒 Iniciar Sesión',
        'registro_titulo' => '📝 Crear Cuenta',
        'email' => 'Email',
        'contrasena' => 'Contraseña',
        'nombre_completo' => 'Nombre completo',
        'confirmar_contrasena' => 'Confirmar contraseña',
        'iniciar_sesion' => 'Iniciar Sesión',
        'crear_cuenta' => 'Crear Cuenta',
        'reserva_titulo' => '➕ Nueva Reserva',
        'habitacion' => 'Habitación',
        'fecha_llegada' => 'Fecha de llegada',
        'fecha_salida' => 'Fecha de salida',
        'documento_identidad' => 'Documento de Identidad',
        'crear_reserva' => 'Crear Reserva',
        'bienvenido' => 'Bienvenido',
        'usuario' => 'Usuario',
        'administrador' => 'Administrador',
        'cerrar_sesion' => 'Cerrar Sesión',
        'huéspedes_reales' => '🏨 Huéspedes Reales (Han hecho al menos una reserva)',
        'usuarios_registrados' => '👥 Usuarios Registrados (Pueden hacer login)',
        'gestion_reservas' => '📅 Gestionar Reservas',
        'gestion_habitaciones' => '🛏️ Gestionar Habitaciones y Limpieza',
        'gestion_mantenimiento' => '🔧 Registrar Tareas de Mantenimiento',
        'no_huespedes' => 'No hay huéspedes reales (ningún usuario ha hecho una reserva aún).',
        'no_usuarios' => 'No hay usuarios registrados.',
        'documento_obligatorio' => 'El documento de identidad es obligatorio para tu primera reserva.',
        'reserva_exito' => '✅ Reserva creada con éxito.',
        'email_contrasena_incorrectos' => 'Email o contraseña incorrectos.',
        'ya_tienes_cuenta' => '¿Ya tienes cuenta?',
        'no_tienes_cuenta' => '¿No tienes cuenta?',
        'registrar_aqui' => 'Regístrate aquí',
        'iniciar_aqui' => 'Iniciar sesión',
        'credenciales_prueba' => 'Credenciales de prueba:',
        // Nuevas claves para admin/index.php
        'panel_admin' => 'Panel de Administración - SGH',
        'conectado_como' => 'Conectado como',
        'descripcion_usuarios_registrados' => 'Estos usuarios están registrados en el sistema pero aún no han hecho ninguna reserva.',
        'nombre' => 'Nombre',
        'rol' => 'Rol',
        'id' => 'ID',
        'huesped' => 'Huésped',
        'fechas' => 'Fechas',
        'precio' => 'Precio',
        'acciones' => 'Acciones',
        'confirmar' => 'Confirmar',
        'cancelar' => 'Cancelar',
        'numero' => 'Número',
        'tipo' => 'Tipo',
        'estado_limpieza' => 'Estado Limpieza',
        'accion' => 'Acción',
        'limpia' => 'Limpia',
        'sucia' => 'Sucia',
        'en_limpieza' => 'En Limpieza',
        'guardar' => 'Guardar',
        'fecha_inicio' => 'Fecha de inicio',
        'fecha_fin' => 'Fecha de fin',
        'registrar_tarea' => 'Registrar Tarea',
        'tareas_registradas' => 'Tareas registradas',
        'placeholder_descripcion_mantenimiento' => 'Ej: Arreglar grifo',
        'seleccionar_habitacion' => '-- Seleccione --',
        'seleccionar' => 'Seleccione',
        'ya_huesped_registrado' => 'Ya eres huésped registrado',
        'tipo_habitacion_simple' => 'Simple',
        'tipo_habitacion_doble' => 'Doble',
        'tipo_habitacion_suite' => 'Suite',
        'descripcion' => 'Descripción',
        'estado' => 'Estado',
        'pendiente' => 'Pendiente',
        'confirmada' => 'Confirmada',
        'cancelada' => 'Cancelada',
        'activo' => 'Activa',
        'reserva_actualizada' => '✅ Reserva actualizada correctamente.',
        'error_actualizar' => '❌ Error al actualizar.',
        'limpieza_actualizada' => '✅ Estado de limpieza actualizado.',
        'mantenimiento_registrado' => '✅ Tarea de mantenimiento registrada.',
        'todos_campos_obligatorios' => 'Todos los campos son obligatorios.',
        'fecha_fin_posterior_inicio' => 'La fecha de fin debe ser posterior a la de inicio.',
        'estado_no_valido' => 'Estado no válido.',
        'tarea_cancelada' => 'Tarea cancelada.',
        'reserva_confirmada' => 'Reserva confirmada.',
        'reserva_cancelada' => 'Reserva cancelada.',
        'habitacion_no_disponible' => 'La habitación ya está reservada en esas fechas.',
        'mantenimiento_activo' => 'La habitación tiene mantenimiento activo en esas fechas.',
        'documento_obligatorio_reserva' => 'El documento de identidad es obligatorio para tu primera reserva.',
        'reserva_creada_exito' => '✅ Reserva creada con éxito.',
        'email_o_contrasena_incorrectos' => 'Email o contraseña incorrectos.',
        'ya_tienes_cuenta' => '¿Ya tienes cuenta?',
        'no_tienes_cuenta' => '¿No tienes cuenta?',
        'registrar_aqui' => 'Regístrate aquí',
        'iniciar_aqui' => 'Iniciar sesión',
        'credenciales_prueba' => 'Credenciales de prueba:'
    ],
    'en' => [
        'hotel_nombre' => 'The Great Rest Hotel',
        'login_titulo' => 'Login',
        'registro_titulo' => 'Create Account',
        'email' => 'Email',
        'contrasena' => 'Password',
        'nombre_completo' => 'Full Name',
        'confirmar_contrasena' => 'Confirm Password',
        'iniciar_sesion' => 'Login',
        'crear_cuenta' => 'Create Account',
        'reserva_titulo' => 'New Reservation',
        'habitacion' => 'Room',
        'fecha_llegada' => 'Check-in Date',
        'fecha_salida' => 'Check-out Date',
        'documento_identidad' => 'ID Document',
        'crear_reserva' => 'Create Reservation',
        'bienvenido' => 'Welcome',
        'usuario' => 'User',
        'administrador' => 'Administrator',
        'cerrar_sesion' => 'Logout',
        'huéspedes_reales' => 'Real Guests (Have made at least one reservation)',
        'usuarios_registrados' => 'Registered Users (Can login)',
        'gestion_reservas' => 'Manage Reservations',
        'gestion_habitaciones' => 'Manage Rooms and Cleaning',
        'gestion_mantenimiento' => 'Register Maintenance Tasks',
        'no_huespedes' => 'No real guests yet (no user has made a reservation).',
        'no_usuarios' => 'No registered users.',
        'documento_obligatorio' => 'ID document is required for your first reservation.',
        'reserva_exito' => 'Reservation created successfully.',
        'email_contrasena_incorrectos' => 'Incorrect email or password.',
        'ya_tienes_cuenta' => 'Already have an account?',
        'no_tienes_cuenta' => 'Don\'t have an account?',
        'registrar_aqui' => 'Register here',
        'iniciar_aqui' => 'Login',
        'credenciales_prueba' => 'Test credentials:',
        // Nuevas claves para admin/index.php
        'panel_admin' => 'Admin Panel - SGH',
        'conectado_como' => 'Logged in as',
        'descripcion_usuarios_registrados' => 'These users are registered but have not made any reservations yet.',
        'nombre' => 'Name',
        'rol' => 'Role',
        'id' => 'ID',
        'huesped' => 'Guest',
        'fechas' => 'Dates',
        'precio' => 'Price',
        'acciones' => 'Actions',
        'confirmar' => 'Confirm',
        'cancelar' => 'Cancel',
        'numero' => 'Number',
        'tipo' => 'Type',
        'estado_limpieza' => 'Cleaning Status',
        'accion' => 'Action',
        'limpia' => 'Clean',
        'sucia' => 'Dirty',
        'en_limpieza' => 'Being Cleaned',
        'guardar' => 'Save',
        'fecha_inicio' => 'Start Date',
        'fecha_fin' => 'End Date',
        'registrar_tarea' => 'Register Task',
        'tareas_registradas' => 'Registered Tasks',
        'placeholder_descripcion_mantenimiento' => 'E.g: Fix faucet',
        'seleccionar_habitacion' => '-- Select --',
        'seleccionar' => 'Select',
        'ya_huesped_registrado' => 'You are already a registered guest',
        'tipo_habitacion_simple' => 'Single',
        'tipo_habitacion_doble' => 'Double',
        'tipo_habitacion_suite' => 'Suite',
        'descripcion' => 'Description',
        'estado' => 'Status',
        'pendiente' => 'Pending',
        'confirmada' => 'Confirmed',
        'cancelada' => 'Cancelled',
        'activo' => 'Active',
        'reserva_actualizada' => 'Reservation updated successfully.',
        'error_actualizar' => 'Error updating.',
        'limpieza_actualizada' => 'Cleaning status updated.',
        'mantenimiento_registrado' => 'Maintenance task registered.',
        'todos_campos_obligatorios' => 'All fields are required.',
        'fecha_fin_posterior_inicio' => 'End date must be after start date.',
        'estado_no_valido' => 'Invalid status.',
        'tarea_cancelada' => 'Task cancelled.',
        'reserva_confirmada' => 'Reservation confirmed.',
        'reserva_cancelada' => 'Reservation cancelled.',
        'habitacion_no_disponible' => 'The room is already booked for those dates.',
        'mantenimiento_activo' => 'The room has active maintenance for those dates.',
        'documento_obligatorio_reserva' => 'ID document is required for your first reservation.',
        'reserva_creada_exito' => 'Reservation created successfully.',
        'email_o_contrasena_incorrectos' => 'Incorrect email or password.',
        'ya_tienes_cuenta' => 'Already have an account?',
        'no_tienes_cuenta' => 'Don\'t have an account?',
        'registrar_aqui' => 'Register here',
        'iniciar_aqui' => 'Login',
        'credenciales_prueba' => 'Test credentials:'
    ]
];

// Función para obtener texto traducido
function t($clave) {
    global $textos, $idioma;
    return $textos[$idioma][$clave] ?? $clave;
}
?>